# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  gnome-shell-mobile = {
    pname = "gnome-shell-mobile";
    version = "4ef0db259a1815d00656c3adab89df14f272067e";
    src = fetchgit {
      url = "https://gitlab.gnome.org/verdre/gnome-shell";
      rev = "4ef0db259a1815d00656c3adab89df14f272067e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-pIBJFyg1XDVrZdPhbDYdSGrDEwa1xTT4gSnF7z7tLpw=";
    };
  };
  mutter-mobile = {
    pname = "mutter-mobile";
    version = "4e6674075cfd7e644da14837a661ed3a1fb0395b";
    src = fetchgit {
      url = "https://gitlab.gnome.org/verdre/mutter";
      rev = "4e6674075cfd7e644da14837a661ed3a1fb0395b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-AgisT14I22q8VEkc7IionZmZi89KMEHBVwQLVdL22Ck=";
    };
  };
}
